SX2-1699 Add animal bulk to slate docu.
smaxtec/slate pull request #12
Opened 2021-11-11 12:41 UTC by smaXtecStefan

added animal bulk upload

2021-11-15 15:23 UTC, smaXtecStefan commented on source/index.html.md
> +route = endpoint + '/organisations/' + organisation_id + '/animals' + optional_parameters
the route needs to be without the `optional_parameters`.

2021-11-15 15:23 UTC, smaXtecStefan commented on source/index.html.md
> +r = requests.put(route, headers=headers)
the put call needs the `json=data` parameter where data are the animals which should get integrated into our system

2021-11-15 15:23 UTC, smaXtecStefan commented on source/index.html.md
> +        -H  "User-Agent: [user_agent]"
the `-d ...` flag needs to be added as well

2021-11-15 15:23 UTC, smaXtecStefan commented on source/index.html.md
> +| include_archived | Include archived animals.                           | default: `false` |
the `include_archived` isn't an accepted parameter. this needs to be deleted.

instead the animals should be put here. you can reference to the parameters from **Create/Update Single Animal**

2021-11-15 15:23 UTC, smaXtecStefan commented on source/index.html.md
> +## Put Animals
to be consistent with the other subsections please change this to **Create/Update Multiple Animals**

2022-01-25 13:33 UTC, KrennKristof requested changes

2022-01-25 13:33 UTC, KrennKristof commented on source/index.html.md
> +        -H  "User-Agent: [user_agent]"
in line 455 there is one " missing at organisation_id

2022-08-24 08:41 UTC, closed without merging

2022-08-24 08:41 UTC, KrennKristof commented
closed, documentation moved to gitlab